INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1001','PHP best book','tom',11.2,121);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1002','PHP basic book','tom',11.2,110);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1003','php book1','tom',11.2,11);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1004','best php book','tom',11.2,151);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1005','Javascript best book','tom',11.2,101);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1006','PHP best book','tom',11.2,121);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1007','PHP basic book','tom',11.2,110);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1008','php book1','tom',11.2,11);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1009','best php book','tom',11.2,151);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1010','Javascript best book','tom',11.2,101);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1011','Java best book','tom',11.2,11);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1012','PHP JavaScript book','tom',11.2,181);
INSERT INTO books (product_id,product_title,product_author,product_price,product_inventory)VALUES('1013','JavaScript book','tom',11.2,171);
