-- MySQL Script generated by MySQL Workbench
-- Tue May 26 06:55:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ebookshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebookshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebookshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ebookshop` ;

-- -----------------------------------------------------
-- Table `ebookshop`.`creditcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`creditcard` (
  `creditID` INT NOT NULL AUTO_INCREMENT,
  `invoiceID` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `CreditCardType` VARCHAR(45) NULL DEFAULT NULL,
  `CreditCardNumber` VARCHAR(45) NULL DEFAULT NULL,
  `CreditCardExpirationDate` VARCHAR(45) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`creditID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ebookshop`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`Contact` (
  `contactID` INT NOT NULL AUTO_INCREMENT,
  `invoiceID` VARCHAR(45) NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `CompanyName` VARCHAR(45) NULL DEFAULT NULL,
  `Address1` VARCHAR(45) NULL DEFAULT NULL,
  `Address2` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  `Zip` VARCHAR(45) NULL DEFAULT NULL,
  `Country` VARCHAR(45) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `creditID` INT NOT NULL,
  PRIMARY KEY (`contactID`, `creditID`),
  INDEX `invoiceID` (`invoiceID` ASC),
  INDEX `fk-creditID_idx` (`creditID` ASC),
  CONSTRAINT `fk-creditID`
    FOREIGN KEY (`creditID`)
    REFERENCES `ebookshop`.`creditcard` (`creditID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ebookshop`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`books` (
  `id` INT NOT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `author` VARCHAR(50) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `qty` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ebookshop`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`cart` (
  `cartID` INT NOT NULL,
  `product_id` VARCHAR(45) NOT NULL,
  `product_price` DOUBLE NULL DEFAULT NULL,
  `product_quantity` INT NULL DEFAULT NULL,
  `product_totalprice` DOUBLE NULL DEFAULT NULL,
  `product_title` VARCHAR(45) NULL DEFAULT NULL,
  `product_author` VARCHAR(45) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `books_id` INT NOT NULL,
  PRIMARY KEY (`cartID`),
  INDEX `fk_cart_books1_idx` (`books_id` ASC),
  CONSTRAINT `fk_cart_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `ebookshop`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 99
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ebookshop`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`email` (
  `email` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ebookshop`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`invoice` (
  `invoiceID` VARCHAR(45) NOT NULL,
  `cartID` INT NULL,
  `contactID` INT NOT NULL,
  PRIMARY KEY (`invoiceID`, `contactID`),
  INDEX `fk-contactID_idx` (`contactID` ASC),
  INDEX `fk-cartID_idx` (`cartID` ASC),
  CONSTRAINT `fk-contactID`
    FOREIGN KEY (`contactID`)
    REFERENCES `ebookshop`.`Contact` (`contactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-cartID`
    FOREIGN KEY (`cartID`)
    REFERENCES `ebookshop`.`cart` (`cartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebookshop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `hashpassword` VARCHAR(256) NULL DEFAULT NULL,
  `salt` VARCHAR(256) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`, `username`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ebookshop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebookshop`.`order` (
  `orderID` INT NOT NULL,
  `cartID` INT NULL,
  `invoiceID` VARCHAR(45) NOT NULL DEFAULT NULL,
  `userID` INT NULL,
  `orderDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`orderID`, `invoiceID`),
  INDEX `fk-cartID_idx` (`cartID` ASC),
  INDEX `fk-invoiceID_idx` (`invoiceID` ASC),
  INDEX `fk-userID_idx` (`userID` ASC),
  CONSTRAINT `fk-cartID`
    FOREIGN KEY (`cartID`)
    REFERENCES `ebookshop`.`cart` (`cartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-invoiceID`
    FOREIGN KEY (`invoiceID`)
    REFERENCES `ebookshop`.`invoice` (`invoiceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-userID`
    FOREIGN KEY (`userID`)
    REFERENCES `ebookshop`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
